version: "3.7"
services:

    #Laravel App
    app:
        build:
            args:
                user: suhrob
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - mynetwork

    #Nginx Service
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - mynetwork
    #Mysl Service
    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
